FROM node:latest

WORKDIR /usr/app/src

COPY /nodeApp/index.js /usr/app/src
COPY /nodeApp/package*.json /usr/app/src

RUN chmod 777 index.js
RUN npm install

EXPOSE 3000

ENTRYPOINT ["node", "index.js"]